apiVersion: apps/v1
kind: Deployment
metadata:
  name: themed-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: themed-web
  template:
    metadata:
      labels:
        app: themed-web
    spec:
      containers:
        - name: themed-web
          image: my-themed-web-app:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
